package Models;
// Generated Oct 28, 2020 1:56:33 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Property generated by hbm2java
 */
public class Property  implements java.io.Serializable {


     private int propertyId;
     private Owner owner;
     private String district;
     private Integer price;
     private Boolean available;
     private Serializable pictures;
     private Set reservations = new HashSet(0);

    public Property() {
    }

	
    public Property(int propertyId) {
        this.propertyId = propertyId;
    }
    public Property(int propertyId, Owner owner, String district, Integer price, Boolean available, Serializable pictures, Set reservations) {
       this.propertyId = propertyId;
       this.owner = owner;
       this.district = district;
       this.price = price;
       this.available = available;
       this.pictures = pictures;
       this.reservations = reservations;
    }
   
    public int getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(int propertyId) {
        this.propertyId = propertyId;
    }
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Boolean getAvailable() {
        return this.available;
    }
    
    public void setAvailable(Boolean available) {
        this.available = available;
    }
    public Serializable getPictures() {
        return this.pictures;
    }
    
    public void setPictures(Serializable pictures) {
        this.pictures = pictures;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


