package Models;
// Generated Oct 28, 2020 1:56:33 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private int reservationId;
     private Property property;
     private Tenant tenant;
     private Date beginDate;
     private Date endDate;

    public Reservation() {
    }

	
    public Reservation(int reservationId) {
        this.reservationId = reservationId;
    }
    public Reservation(int reservationId, Property property, Tenant tenant, Date beginDate, Date endDate) {
       this.reservationId = reservationId;
       this.property = property;
       this.tenant = tenant;
       this.beginDate = beginDate;
       this.endDate = endDate;
    }
   
    public int getReservationId() {
        return this.reservationId;
    }
    
    public void setReservationId(int reservationId) {
        this.reservationId = reservationId;
    }
    public Property getProperty() {
        return this.property;
    }
    
    public void setProperty(Property property) {
        this.property = property;
    }
    public Tenant getTenant() {
        return this.tenant;
    }
    
    public void setTenant(Tenant tenant) {
        this.tenant = tenant;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


