package Models;
// Generated Oct 28, 2020 1:56:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tenant generated by hbm2java
 */
public class Tenant  implements java.io.Serializable {


     private int tenantId;
     private String lastName;
     private String firstName;
     private String email;
     private Integer phone;
     private Integer propertyId;
     private Set reservations = new HashSet(0);

    public Tenant() {
    }

	
    public Tenant(int tenantId) {
        this.tenantId = tenantId;
    }
    public Tenant(int tenantId, String lastName, String firstName, String email, Integer phone, Integer propertyId, Set reservations) {
       this.tenantId = tenantId;
       this.lastName = lastName;
       this.firstName = firstName;
       this.email = email;
       this.phone = phone;
       this.propertyId = propertyId;
       this.reservations = reservations;
    }
   
    public int getTenantId() {
        return this.tenantId;
    }
    
    public void setTenantId(int tenantId) {
        this.tenantId = tenantId;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getPhone() {
        return this.phone;
    }
    
    public void setPhone(Integer phone) {
        this.phone = phone;
    }
    public Integer getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


